Ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls'))
]

shop/urls.py
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from shop import views

urlpatterns = [
    
    path('',views.base,name='home'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('view/<int:id>',views.viewdata,name="viewdata"),
    path('search/',views.searchdata,name='searchdata'),
    path('logout/',views.logout,name='logout'),
    path('addtocart/<int:id>',views.AddtocartView.as_view(),name='addtocart'),
    path('cart/',views.cart,name='cart'),
    path('shipping/',views.shippinginfo,name='shipping'),
    path('managecart/<int:cp_id>/',views.managecart,name='managecart'),
    path('empty/',views.emptycart,name='empty')
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models



class User(models.Model):
    fullname=models.CharField(max_length=200)
    email=models.EmailField()
    password=models.CharField(max_length=200)
    passwordagain=models.CharField(max_length=200)
    phoneno=models.CharField(max_length=200)
    city=models.CharField(max_length=200)

    def isExist(self):
        if User.objects.filter(email=self.email):#for unique email 
            return True
        else:
            return False
    def is_exist(self):
        if User.objects.filter(phoneno=self.phoneno):#foe unique phonenumber
           return True
        else:
            return False  
    @staticmethod
    def get_customer_email(email):
        try:
          return User.objects.get(email=email)   
        except:
          return False



class Category(models.Model):
    name=models.CharField(max_length=200)

    def _str_(self):
        return self.name
    @staticmethod
    def get_all_categories():
        return Category.objects.all() 



class Product(models.Model):
    name=models.CharField(max_length=200)
    category=models.ForeignKey(Category,on_delete=models.CASCADE,default=1)
    price=models.FloatField()
    image=models.ImageField(null=True,blank=True)

 


    def _str_(self):
        return self.name

    @staticmethod
    def get_all_products():
        return Product.objects.all()    

    @property
    def imageURL(self):#for getting image url
        try:
            url=self.image.url
        except:
            url=''
        return url          
    @staticmethod
    def get_all_product_by_id(category_id):#filtering categories
        if category_id:
           return Product.objects.filter(category=category_id)
        else:
            return Product.get_all_products()

class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.SET_NULL,null=True,blank=True)
    total=models.PositiveIntegerField(default=0)

    def __str__(self):
        return "cart:"+str(self.id)

class CartProduct(models.Model):
    cart=models.ForeignKey(Cart,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    rate=models.PositiveIntegerField()
    quantity=models.PositiveIntegerField()
    subtotal=models.PositiveIntegerField()

    def __str__(self):
        return "cart:"+str(self.cart.id) + "cartproduct:"+str(self.id)

class ShippingAddress(models.Model):
	userr = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
	cardproduct = models.ForeignKey(CartProduct, on_delete=models.SET_NULL, null=True)
	address = models.CharField(max_length=200, null=False)
	city = models.CharField(max_length=200, null=False)
	state = models.CharField(max_length=200, null=False)
	zipcode = models.CharField(max_length=200, null=False)



	def _str_(self):
		return self.address
        

templates/addtocart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mx-auto mt-5">
<h2> Product added to cart succesfullly..!!! Go to cart for more....<a  href="/cart/" class="btn btn-outline-success btn-lg"><b>Cart</b></a></h2>

</div>



{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>E-shop</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/home.css' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-dark">
      <a class="navbar-brand" href="{% url 'home' %}"></a>
        <img src="{% static 'images/shop3.jfif'%}" alt="" width="60" height="48">
      </a>
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home' %}"><h2><b>E-SHOP</b></h2></a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}"><h4>STORE</h4></a>
        </li>
        <div>
          <form method="get" action ="/search"class="d-flex">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search" id="search">
            <button class="btn btn-outline-warning" type="submit"><b>Search</b></button>
          </form>
        </div>
    </div>
    </div>
   

    <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <li class="nav-item dropdown">
                {% if request.session.user %}
                <li class="nav-item">
                  
                    <a class="nav-link active" aria-current="page" href="/logout"><b>LogOut</b></a>
                  </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/login"><b>Login</b></a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/signup"><b>Signup</b></a>
                  </li>
                {% endif %}
                
                  
                <li class="nav-item ml-5">
                  <a  href="/cart/"> 
                    <img class="thumbnail" src="{% static 'images/cartimg.jfif' %}"width="50px" height="50px">
                  </a>
                </li>
                
                  </li>
              </li>
        </li>
        
        </ul>
</nav>
{% block content%}{% endblock %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>

	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
 

</body>
</html>

templates/cart.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>cart</title>
</head>
<body>
    <div class="cointainer mt-5">
    <hr>
    <div class="container mt-5">
        <div class="row">
          <div class="col-sm-9">
            <a class="btn btn-success" href="{% url 'home' %}" role="button">&#x2190; ContinueShopping</a>
          </div>
          <div class="col-sm-3">
            <a class="btn btn-success" href="{% url 'shipping' %}" role="button"> CheckOut&#8594; </a>
          </div>
        </div>
      </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-8 mx-auto">

            <table class="table">
                <thead>
                    <tr>
                        <th class="table-success"><b>Sr.No</b></th>
                        <th class="table-success"><b>Product</b></th>
                        <th class="table-success"><b>Image</b></th>
                        <th class="table-success"><b>Price</b></th>
                        <th class="table-success"><b>Quantity</b></th>
                        <th class="table-success"><b>SubTotal</b></th>
                        <th class="table-success"><b>Action</b></th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cartobj %}
                    <tr>
                        <td><b>{{forloop.counter}}</b</td>
                        <td><b>{{cp.product.name}}</b</td>
                       <td><img class="row-image" src="{{cp.product.image.url}}"width="75px" height="80px"></td>
                        <td><b>{{cp.rate}}</td>
                        <td><b>{{cp.quantity}}</b</td>
                        <td><b>{{cp.subtotal}}</b</td>
                        <td>
                            <a href="/managecart/{{cp.id}}?action=inc" class="btn btn-outline-success"><b>+</b> </a>
                            <a href="/managecart/{{cp.id}}?action=dcr" class="btn btn-outline-warning"> <b>-</b></a>
                            <a href="/managecart/{{cp.id}}?action=rmv" class="btn btn-outline-danger"><b>X</b>
                        </td>
                    </tr>
                    {% endfor %}
                   <tr>
                       <th colspan="5" class="text-right"></th>
                       <th><b>Total Rs{{cart.total}}</b></th>
                       {% if cart.cartproduct_set %}
                       <th><a href="/empty/" class="btn btn-danger"><b>EmptyCart</b></th>
                       {% endif %}
                   </tr> 
                   </div>
                   
                   
    </div>
                    

</body> 
</html>                   

templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class="container-fluid mt-5">
  <!---row class in bootstrap for items in rows otherwise will shown in coloumn-->
<div class="row">
  <!--filter-->
<div class="col-lg-3 mx-auto">
  <div class="list-group">
    {% for category in categories %}
    <!--/?category={{category.id}} query set url for getting filter categories wise-->
    <a href="/?category={{category.id}}" class="list-group-item list-group-item">
    <b>{{category.name}}</b>
    </a>
    {% endfor %}
  </div>
<!--col-log-3 means out of 12 rows 3applied-->
</div>

  <!--Products-->
  <div id="product" class="col-lg-9 mx-auto">
    <div class="row mx-auto">
      {% for product in products %}
      <div class="card mx-auto mb-5" style="width: 18rem;">
          <img class="thumbnail" src="{{product.imageURL}}"width="150px" height="170px">
          <div class="card-body ">
            <h5 class="card-title"><b>Product:{{product.name}}</b></h5>
            <p class="card-text"><h6><b>Price:{{product.price}}Rs</b></h6></p>
            <a  href="/addtocart/{{product.id}}" id="qv{{product.id}}" class="btn btn-success cart">Add to cart</a>
          <a  href="/view/{{product.id}}" id="qv{{product.id}}" class="btn btn-success cart">View</a>
          </div>
      </div>
      {% endfor %}
  </div> 
</div>
</div>
</div>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<div class="container mx-auto mt-5 col-lg-4 border=2px">
<h2>Login Here.....</h2>
</div>

<form action="#" method="post">
    {% csrf_token %}
    {% if error %}
        <div class="alert alert-danger" role="alert">
            {{error}}
        </div>
        
    {% endif %}
    
    <div class="col-lg-7  mx-auto border rounded mt-5 p-5">
    
    <div class="form-floating mb-1 mt-3 col-lg-4 mx-auto">
        
        <input required type="email" class="form-control" name="email" placeholder="name@example.com">
        <label for="">Email address</label>
      </div>
      <div class="form-floating mb-1 col-lg-4 mx-auto">
        <input required type="password" class="form-control" name="password" placeholder="Password">
        <label for="">Password</label>
      </div>
      <div class="col-lg-4 mt-3 mx-auto mb-5">
        <button type="submit" class="btn btn-primary">Login</button>
      </div>
  </form>
</div>
{% endblock %}

templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
   <h2>Logout succesfullly!!!!!!!!!!!!</h2> 
   <h3>Thank You....</h3>
</body>
</html>

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h2>Search Results.....</h2>
    

<div class="container-fluid mt-5">
    <div id="product" class="col-lg-9 mx-auto">
       
  <!---row class in bootstrap for items in rows otherwise will shown in coloumn-->
<div class="row">
  <!--filter-->
<div class="col-lg-3 mx-auto">
  <div class="list-group">
    {% for category in categories %}
    <!--/?category={{category.id}} query set url for getting filter categories wise-->
    <a href="/?category={{category.id}}" class="list-group-item list-group-item">
    <b>{{category.name}}</b>
    </a>
    {% endfor %}
  </div>
<!--col-log-3 means out of 12 rows 3applied-->
</div>

  <!--Products-->
  
    {% for product in products %}
    
    <div class="row mx-auto">
        
      <div class="card mx-auto mb-5" style="width: 18rem;">
          <img class="thumbnail" src="{{product.imageURL}}"width="150px" height="170px">
          <div class="card-body ">
            <h5 class="card-title"><b>Product:{{product.name}}</b></h5>
            <p class="card-text"><h6><b>Price:{{product.price}}Rs</b></h6></p>
            <a  href="/addtocart/{{product.id}}" id="qv{{product.id}}" class="btn btn-success cart">Add to cart</a>
          <a  href="/view/{{product.id}}" id="qv{{product.id}}" class="btn btn-success cart">View</a>
          </div>
      </div>

    {% empty %}  
    <p><b> No Search Results.....!!!</b></p>
    Your search <b>{{search}}</b>-did not match any document</b>
    <li> Try different keywords</li>
    {% endfor %}
  </div> 
</div>
</div>
</div>
{% endblock %}

templates/shippingform.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <title>cart</title>
</head>
<body>
    <div class="container mx-auto mt-5">
<h3>CheckOut:

</h3>
</div>

<div class="container mt-5"> 
    <div class="row">
      <div class="col-sm-6">
        <div class="box-element" id="form-wrapper">
            <form id="form">
                <div id="user-info">
                    <div class="form-field">
                        <input required class="form-control" type="text" name="name" placeholder="Name..">
                    </div>
                    <div class="form-field">
                        <input required class="form-control" type="email" name="email" placeholder="Email..">
                    </div>
                </div>
                
                <div id="shipping-info">
                    <hr>
                    <p>Shipping Information:</p>
                    <hr>
                    <div class="form-field">
                        <input class="form-control" type="text" name="address" placeholder="Address..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="city" placeholder="City..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="state" placeholder="State..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="zipcode" placeholder="Zip code..">
                    </div>
                    <div class="form-field">
                        <input class="form-control" type="text" name="country" placeholder="Country..">
                    </div>
                </div>

                <hr>
                <input id="form-button" class="btn btn-warning btn-block" type="submit" value="Continue">
            </form>
            <div class="my-3">
                <hr>
                <h4>Payments</h4>
                <hr>
                <div class="form-check">
                  <input id="credit" name="paymentMethod" type="radio" class="form-check-input" checked="" required="">
                  <label class="form-check-label" for="credit">Credit card</label>
                </div>
                <div class="form-check">
                  <input id="debit" name="paymentMethod" type="radio" class="form-check-input" required="">
                  <label class="form-check-label" for="debit">Debit card</label>
                </div>
                <div class="form-check">
                  <input id="paypal" name="paymentMethod" type="radio" class="form-check-input" required="">
                  <label class="form-check-label" for="paypal">Cash On delivery</label>
                  <div class="row gy-3">
                    <div class="col-md-6">
                      <label for="cc-name" class="form-label">Name on card</label>
                      <input type="text" class="form-control" id="cc-name" placeholder="" required="">
                      <small class="text-muted">Full name as displayed on card</small>
                      <div class="invalid-feedback">
                        Name on card is required
                      </div>
                    </div>
        
                    <div class="col-md-6">
                      <label for="cc-number" class="form-label">Credit card number</label>
                      <input type="text" class="form-control" id="cc-number" placeholder="" required="">
                      <div class="invalid-feedback">
                        Credit card number is required
                      </div>
                    </div>
        
                    <div class="col-md-3">
                      <label for="cc-expiration" class="form-label">Expiration</label>
                      <input type="text" class="form-control" id="cc-expiration" placeholder="" required="">
                      <div class="invalid-feedback">
                        Expiration date required
                      </div>
                    </div>
        
                    <div class="col-md-3">
                      <label for="cc-cvv" class="form-label">CVV</label>
                      <input type="text" class="form-control" id="cc-cvv" placeholder="" required="">
                      <div class="invalid-feedback">
                        Security code required
                        <button class="w-100 btn btn-primary btn-lg" type="submit">Continue to checkout</button>
                      </div>
                      <div class="container mt-5">
                        <button class=" btn btn-warning" type="submit">PlaceOrder</button>
                    </div>
                    </div>
                  </div>
                </div>
              </div>
        </div>

        <br>
      </div>
      <div class="col-sm-6 "  >
        <div class="col-lg-6">
			<div class="box-element">
				<a  class="btn btn-outline-dark" href="{% url 'cart' %}">&#x2190; Back to Cart</a>
				<hr>
				<h3>Order Summary</h3>
				<hr>
				{% for item in cartobj %}
				<div class="cart-row">
					<div style="flex:2"><img class="row-image" src="{{item.product.image.url}}"width="120px" height="120px"></div>
					<div style="flex:2"><p>Product{{item.product.name}}</p></div>
					<div style="flex:1"><p>Rs{{item.product.price|floatformat:2}}</p></div>
					<div style="flex:1"><p>Quantity{{item.quantity}}</p></div>
				</div>
				{% endfor %}
				<h5>Total:   Rs{{cart.total|floatformat:2}}</h5>
			</div>
      </div>
    </div>
  </div>
      
</body>
</html>

templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mx-auto mt-5"><!--mt=margin to,mx-auto means it gets to center-->
<h2>Create an Account </h2>
</div>
<div class="container">
    <form class="row g-3" action="#" method="post">
        {% csrf_token %}
        <!--adding error or sucess msg aler in div with ifonly excuted when there is need -->
        {% if message %}
        <div class="alert alert-success" role="alert">
            {{message}}
        </div>
        {% endif %}
        {% if error %}
        <div class="alert alert-danger" role="alert">
            {{error}}
        </div>
        {% endif %}
        <div class="col-md-6">
            <label for="" class="form-label">Full Name</label>
            <input required type="text" value="{{value.fullname}}"class="form-control" name="fullname">
          </div>
        <div class="col-md-6">
          <label for="inputEmail4" class="form-label">Email</label>
          <input required type="email" value="{{value.email}}"class="form-control" name="email">
        </div>
        <div class="col-md-6">
          <label for="" class="form-label">Password</label>
          <input required type="password"  class="form-control" name="password">
        </div>
        <div class="col-md-6">
            <label for="" class="form-label">Password Again</label>
            <input required type="password" class="form-control" name="passwordagain">
          </div>
        <div class="col-md-6">
            <label for="" class="form-label">Phone Number</label>
            <input required type="text" value="{{value.phoneno}}" class="form-control" name="phoneno">
          </div>
        <div class="col-md-6">
          <label for="inputCity" class="form-label">City</label>
          <input required type="text" value="{{value.city}}" class="form-control" name="city">
        </div>
        <div class="col-12">
          <button type="submit" class="btn btn-primary">Create an account</button>
        </div>
      </form>
</div>
{% endblock %}

templates/view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
{% for product in products %}
<div class="card mx-auto mb-5 mt-5" style="width: 18rem;">
        <img class="thumbnail" src="{{product.imageURL}}"width="250px" height="340px">
          <div class="card-body ">
            <h5 class="card-title"><h5><b>Product:{{product.name}}</b></h5>
            <p class="card-text"><h6><b>Price:{{product.price}}Rs</b></h6></p>
            <p class="card-text"><h5><b>Category:{{product.category.name}}</b></h5></p>
            <a  href="/addtocart/{{product.id}}" id="qv{{product.id}}" class="btn btn-success">Add to cart</a>

          </div>
          
{% endfor%}


{% endblock %}